# Generated by Django 4.2.7 on 2024-02-19 11:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="options",
        ),
    ]
