# Generated by Django 4.2.7 on 2024-02-19 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("plan", "0001_initial"),
        ("post", "0002_remove_post_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="plan.plan",
            ),
        ),
    ]
