# Generated by Django 4.2.7 on 2024-02-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0003_post_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="photos",
            field=models.ManyToManyField(related_name="posts", to="post.photo"),
        ),
    ]
