# Generated by Django 4.2.7 on 2024-02-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("option", "0001_initial"),
        ("post", "0004_alter_post_photos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postoptionvalue",
            name="values",
        ),
        migrations.AddField(
            model_name="postoptionvalue",
            name="values",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="post_option_values",
                to="option.value",
            ),
        ),
    ]
