# Generated by Django 4.2.7 on 2024-02-19 13:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0005_remove_postoptionvalue_values_postoptionvalue_values"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="category",
            new_name="subcategory",
        ),
    ]
