# Generated by Django 4.2.7 on 2024-02-19 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
        ("post", "0006_rename_category_post_subcategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="subcategory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="common.subcategory",
            ),
        ),
    ]
