# Generated by Django 4.2.7 on 2024-02-19 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
        ("option", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="option",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.category",
            ),
            preserve_default=False,
        ),
    ]
