# Generated by Django 4.2.7 on 2024-02-19 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
        ("option", "0002_option_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="option",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="common.category",
            ),
        ),
    ]
