# Generated by Django 4.2.7 on 2024-02-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plan", "0002_alter_plandetail_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plandetail",
            name="code",
            field=models.CharField(
                blank=True,
                choices=[("VIP", "Vip"), ("TOP", "Top")],
                max_length=255,
                null=True,
            ),
        ),
    ]
